services:
  postgres:
    image: postgres:16

    container_name: sora-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: sora
      POSTGRES_PASSWORD: sora123
      POSTGRES_DB: sora

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: